// Add any additional repositories for your dependencies here.

repositories {
    maven {
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://maven.covers1624.net"
    }
    maven {
        name = "GTNH Maven"
        url = "https://nexus.gtnewhorizons.com/repository/public/"
    }
    maven {
        name = "FalsePattern Maven"
        url = "https://mvn.falsepattern.com/releases"
    }
    maven {
        name = "JitPack"
        url = "https://jitpack.io"
    }
}

